development:
  adapter: postgresql
  encoding: unicode
  database: monedos_development
  pool: 5
  username: Ner0
  password: 56500859

test:
  adapter: postgresql
  encoding: unicode
  database: myapp_test
  pool: 5
  username: myapp
  password: password1